namespace 爸爸的爱;

public class Vocab
{
    public string Word { get; set; }
    public string Meaning { get; set; }
    public string Book { get; set; }
    public string Unit { get; set; }
    // 新增音标字段
    public string? Phonetic { get; set; }
}

public static class VocabRepository
{
    public static List<Vocab> AllVocabs = new()
    {
        // 三年级上册 第一单元
        new Vocab { Word = "book", Meaning = "书", Book = "三年级上册", Unit = "第一单元", Phonetic = "/bʊk/" },
        new Vocab { Word = "pencil", Meaning = "铅笔", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'pensl/" },
        new Vocab { Word = "ruler", Meaning = "尺子", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'ru:lə(r)/" },
        new Vocab { Word = "teacher", Meaning = "教师", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'ti:tʃə(r)/" },
        new Vocab { Word = "eight", Meaning = "八", Book = "三年级上册", Unit = "第一单元", Phonetic = "/eɪt/" },
        new Vocab { Word = "five", Meaning = "五", Book = "三年级上册", Unit = "第一单元", Phonetic = "/faɪv/" },
        new Vocab { Word = "four", Meaning = "四", Book = "三年级上册", Unit = "第一单元", Phonetic = "/fɔ:(r)/" },
        new Vocab { Word = "nine", Meaning = "九", Book = "三年级上册", Unit = "第一单元", Phonetic = "/naɪn/" },
        new Vocab { Word = "one", Meaning = "一", Book = "三年级上册", Unit = "第一单元", Phonetic = "/wʌn/" },
        new Vocab { Word = "seven", Meaning = "七", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'sevn/" },
        new Vocab { Word = "six", Meaning = "六", Book = "三年级上册", Unit = "第一单元", Phonetic = "/sɪks/" },
        new Vocab { Word = "ten", Meaning = "十", Book = "三年级上册", Unit = "第一单元", Phonetic = "/ten/" },
        new Vocab { Word = "three", Meaning = "三", Book = "三年级上册", Unit = "第一单元", Phonetic = "/θri:/" },
        new Vocab { Word = "two", Meaning = "二", Book = "三年级上册", Unit = "第一单元", Phonetic = "/tu:/" },
        new Vocab { Word = "chair", Meaning = "椅子", Book = "三年级上册", Unit = "第一单元", Phonetic = "/tʃeə(r)/, /tʃer/" },
        new Vocab { Word = "desk", Meaning = "书桌", Book = "三年级上册", Unit = "第一单元", Phonetic = "/desk/" },
        new Vocab { Word = "boy", Meaning = "男孩", Book = "三年级上册", Unit = "第一单元", Phonetic = "/bɔɪ/" },
        new Vocab { Word = "girl", Meaning = "女孩", Book = "三年级上册", Unit = "第一单元", Phonetic = "/gɜ:(r)l/" },
        new Vocab { Word = "school", Meaning = "学校", Book = "三年级上册", Unit = "第一单元", Phonetic = "/sku:l/" },
        new Vocab { Word = "crayon", Meaning = "蜡笔", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'kreɪən/" },
        new Vocab { Word = "pen", Meaning = "钢笔", Book = "三年级上册", Unit = "第一单元", Phonetic = "/pen/" },
        new Vocab { Word = "pencil box", Meaning = "铅笔盒", Book = "三年级上册", Unit = "第一单元", Phonetic = "/'pensl ,bɒks/" },
        new Vocab { Word = "hello", Meaning = "喂；你好（招呼用语）", Book = "三年级上册", Unit = "第一单元", Phonetic = "/hə'ləʊ/" },
        new Vocab { Word = "hi", Meaning = "喂；嗨（招呼用户）", Book = "三年级上册", Unit = "第一单元", Phonetic = "/haɪ/" },

        // 三年级上册 第二单元
        new Vocab { Word = "black", Meaning = "黑色；黑色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/blæk/" },
        new Vocab { Word = "blue", Meaning = "蓝色；蓝色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/blu:/" },
        new Vocab { Word = "green", Meaning = "绿色；绿色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/gri:n/" },
        new Vocab { Word = "red", Meaning = "红色；红色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/red/" },
        new Vocab { Word = "yellow", Meaning = "黄色；黄色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/'jeləʊ/" },
        new Vocab { Word = "orange", Meaning = "橙色；橙色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/'ɒrɪndʒ/, /'ɔ:rɪndʒ/" },
        new Vocab { Word = "friend", Meaning = "朋友", Book = "三年级上册", Unit = "第二单元", Phonetic = "/frend/" },
        new Vocab { Word = "brown", Meaning = "棕色；棕色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/braʊn/" },
        new Vocab { Word = "white", Meaning = "白色；白色的", Book = "三年级上册", Unit = "第二单元", Phonetic = "/waɪt/" },
        new Vocab { Word = "window", Meaning = "窗户", Book = "三年级上册", Unit = "第二单元", Phonetic = "/'wɪndəʊ/" },

        // 三年级上册 第三单元
        new Vocab { Word = "ear", Meaning = "耳朵", Book = "三年级上册", Unit = "第三单元", Phonetic = "/ɪə/, /ɪr/" },
        new Vocab { Word = "eye", Meaning = "眼睛", Book = "三年级上册", Unit = "第三单元", Phonetic = "/aɪ/" },
        new Vocab { Word = "face", Meaning = "脸", Book = "三年级上册", Unit = "第三单元", Phonetic = "/feɪs/" },
        new Vocab { Word = "mouth", Meaning = "嘴", Book = "三年级上册", Unit = "第三单元", Phonetic = "/maʊθ/" },
        new Vocab { Word = "nose", Meaning = "鼻子", Book = "三年级上册", Unit = "第三单元", Phonetic = "/nəʊz/" },
        new Vocab { Word = "happy", Meaning = "高兴的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/'hæpi/" },
        new Vocab { Word = "cold", Meaning = "寒冷的；冷的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/kəʊld/" },
        new Vocab { Word = "cool", Meaning = "凉的；凉爽的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/ku:l/" },
        new Vocab { Word = "hot", Meaning = "热的；烫的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/hɒt/, /hɑ:t/" },
        new Vocab { Word = "warm", Meaning = "温暖的；暖和的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/wɔ:(r)m/" },
        new Vocab { Word = "arm", Meaning = "胳膊", Book = "三年级上册", Unit = "第三单元", Phonetic = "/ɑ:(r)m/" },
        new Vocab { Word = "body", Meaning = "身体", Book = "三年级上册", Unit = "第三单元", Phonetic = "/'bɒdi/, /'bɑ:di/" },
        new Vocab { Word = "foot", Meaning = "脚", Book = "三年级上册", Unit = "第三单元", Phonetic = "/fʊt/" },
        new Vocab { Word = "hair", Meaning = "头发", Book = "三年级上册", Unit = "第三单元", Phonetic = "/heə/, /her/" },
        new Vocab { Word = "hand", Meaning = "手", Book = "三年级上册", Unit = "第三单元", Phonetic = "/hænd/" },
        new Vocab { Word = "head", Meaning = "头", Book = "三年级上册", Unit = "第三单元", Phonetic = "/hed/" },
        new Vocab { Word = "leg", Meaning = "腿", Book = "三年级上册", Unit = "第三单元", Phonetic = "/leg/" },
        new Vocab { Word = "doctor", Meaning = "医生", Book = "三年级上册", Unit = "第三单元", Phonetic = "/'dɒktə(r)/" },
        new Vocab { Word = "tired", Meaning = "疲倦的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/'taɪə(r)d/" },
        new Vocab { Word = "left", Meaning = "左", Book = "三年级上册", Unit = "第三单元", Phonetic = "/left/" },
        new Vocab { Word = "sad", Meaning = "难过的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/sæd/" },
        new Vocab { Word = "right", Meaning = "正确的；对的", Book = "三年级上册", Unit = "第三单元", Phonetic = "/raɪt/" },

        // 三年级上册 第四单元
        new Vocab { Word = "brother", Meaning = "兄；弟", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'brʌðə(r)/" },
        new Vocab { Word = "father", Meaning = "父亲；爸爸", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'fɑ:ðə(r)/" },
        new Vocab { Word = "mother", Meaning = "母亲；妈妈", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'mʌðə(r)/" },
        new Vocab { Word = "sister", Meaning = "姐；妹", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'sɪstə(r)/" },
        new Vocab { Word = "short", Meaning = "矮的；短的", Book = "三年级上册", Unit = "第四单元", Phonetic = "/ʃɔ:(r)t/" },
        new Vocab { Word = "tall", Meaning = "高的", Book = "三年级上册", Unit = "第四单元", Phonetic = "/tɔ:l/" },
        new Vocab { Word = "old", Meaning = "老的；年纪大的", Book = "三年级上册", Unit = "第四单元", Phonetic = "/əʊld/" },
        new Vocab { Word = "cake", Meaning = "蛋糕", Book = "三年级上册", Unit = "第四单元", Phonetic = "/keɪk/" },
        new Vocab { Word = "birthday", Meaning = "生日", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'bɜ:(r)θdeɪ/" },
        new Vocab { Word = "party", Meaning = "聚会；派对", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'pɑ:(r)ti/" },
        new Vocab { Word = "family", Meaning = "家；家庭", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'fæməli/" },
        new Vocab { Word = "worker", Meaning = "工人", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'wɜ:(r)kə(r)/" },
        new Vocab { Word = "China", Meaning = "中国", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'tʃaɪnə/" },
        new Vocab { Word = "young", Meaning = "年轻的；岁数不大的", Book = "三年级上册", Unit = "第四单元", Phonetic = "/jʌŋ/" },
        new Vocab { Word = "bus", Meaning = "公共汽车", Book = "三年级上册", Unit = "第四单元", Phonetic = "/bʌs/" },
        new Vocab { Word = "driver", Meaning = "司机", Book = "三年级上册", Unit = "第四单元", Phonetic = "/'draɪvə(r)/" },
        new Vocab { Word = "policeman", Meaning = "警察", Book = "三年级上册", Unit = "第四单元", Phonetic = "/pə'li:smən/" },

        // 三年级下册 第一单元
        new Vocab { Word = "a", Meaning = "一个", Book = "三年级下册", Unit = "第一单元", Phonetic = "/eɪ; ə/" },
        new Vocab { Word = "an", Meaning = "一个（后跟元音）", Book = "三年级下册", Unit = "第一单元", Phonetic = "/æn; ən/" },
        new Vocab { Word = "bird", Meaning = "鸟", Book = "三年级下册", Unit = "第一单元", Phonetic = "/bɜ:(r)d/" },
        new Vocab { Word = "cat", Meaning = "猫", Book = "三年级下册", Unit = "第一单元", Phonetic = "/kæt/" },
        new Vocab { Word = "dog", Meaning = "狗", Book = "三年级下册", Unit = "第一单元", Phonetic = "/dɒg/, /dɔ:g/" },
        new Vocab { Word = "no", Meaning = "不", Book = "三年级下册", Unit = "第一单元", Phonetic = "/nəʊ/" },
        new Vocab { Word = "yes", Meaning = "是的", Book = "三年级下册", Unit = "第一单元", Phonetic = "/jes/" },
        new Vocab { Word = "in", Meaning = "在......里", Book = "三年级下册", Unit = "第一单元", Phonetic = "/ɪn/" },
        new Vocab { Word = "on", Meaning = "在......上", Book = "三年级下册", Unit = "第一单元", Phonetic = "/ɒn/, /ɑ:n/" },
        new Vocab { Word = "under", Meaning = "在......下面", Book = "三年级下册", Unit = "第一单元", Phonetic = "/'ʌndə(r)/" },
        new Vocab { Word = "box", Meaning = "盒；箱", Book = "三年级下册", Unit = "第一单元", Phonetic = "/bɒks/, /bɑ:ks/" },
        new Vocab { Word = "fish", Meaning = "鱼", Book = "三年级下册", Unit = "第一单元", Phonetic = "/fɪʃ/" },
        new Vocab { Word = "duck", Meaning = "鸭子", Book = "三年级下册", Unit = "第一单元", Phonetic = "/dʌk/" },
        new Vocab { Word = "farmer", Meaning = "农民", Book = "三年级下册", Unit = "第一单元", Phonetic = "/'fɑ:(r)mə(r)/" },
        new Vocab { Word = "animal", Meaning = "兽；动物", Book = "三年级下册", Unit = "第一单元", Phonetic = "/'ænɪml/" },
        new Vocab { Word = "cow", Meaning = "母牛；奶牛", Book = "三年级下册", Unit = "第一单元", Phonetic = "/kaʊ/" },
        new Vocab { Word = "farm", Meaning = "农场", Book = "三年级下册", Unit = "第一单元", Phonetic = "/fɑ:(r)m/" },
        new Vocab { Word = "horse", Meaning = "马", Book = "三年级下册", Unit = "第一单元", Phonetic = "/hɔ:(r)s/" },
        new Vocab { Word = "pig", Meaning = "猪", Book = "三年级下册", Unit = "第一单元", Phonetic = "/pɪg/" },
        new Vocab { Word = "sheep", Meaning = "羊；绵羊", Book = "三年级下册", Unit = "第一单元", Phonetic = "/ʃi:p/" },

        // 三年级下册 第二单元
        new Vocab { Word = "monkey", Meaning = "猴子", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'mʌŋki/" },
        new Vocab { Word = "tiger", Meaning = "老虎", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'taɪgə(r)/" },
        new Vocab { Word = "eight", Meaning = "八", Book = "三年级下册", Unit = "第二单元", Phonetic = "/eɪt/" },
        new Vocab { Word = "five", Meaning = "五", Book = "三年级下册", Unit = "第二单元", Phonetic = "/faɪv/" },
        new Vocab { Word = "four", Meaning = "四", Book = "三年级下册", Unit = "第二单元", Phonetic = "/fɔ:(r)/" },
        new Vocab { Word = "nine", Meaning = "九", Book = "三年级下册", Unit = "第二单元", Phonetic = "/naɪn/" },
        new Vocab { Word = "one", Meaning = "一", Book = "三年级下册", Unit = "第二单元", Phonetic = "/wʌn/" },
        new Vocab { Word = "seven", Meaning = "七", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'sevn/" },
        new Vocab { Word = "six", Meaning = "六", Book = "三年级下册", Unit = "第二单元", Phonetic = "/sɪks/" },
        new Vocab { Word = "ten", Meaning = "十", Book = "三年级下册", Unit = "第二单元", Phonetic = "/ten/" },
        new Vocab { Word = "three", Meaning = "三", Book = "三年级下册", Unit = "第二单元", Phonetic = "/θri:/" },
        new Vocab { Word = "two", Meaning = "二", Book = "三年级下册", Unit = "第二单元", Phonetic = "/tu:/" },
        new Vocab { Word = "banana", Meaning = "香蕉", Book = "三年级下册", Unit = "第二单元", Phonetic = "/bə'nɑ:nə/, /bə'nænə/" },
        new Vocab { Word = "bear", Meaning = "熊", Book = "三年级下册", Unit = "第二单元", Phonetic = "/beə/, /ber/" },
        new Vocab { Word = "big", Meaning = "大的", Book = "三年级下册", Unit = "第二单元", Phonetic = "/bɪg/" },
        new Vocab { Word = "short", Meaning = "矮的；短的", Book = "三年级下册", Unit = "第二单元", Phonetic = "/ʃɔ:(r)t/" },
        new Vocab { Word = "zoo", Meaning = "动物园", Book = "三年级下册", Unit = "第二单元", Phonetic = "/zu:/" },
        new Vocab { Word = "grass", Meaning = "草坪", Book = "三年级下册", Unit = "第二单元", Phonetic = "/grɑ:s/, /græs/" },
        new Vocab { Word = "tree", Meaning = "树；树木；乔木", Book = "三年级下册", Unit = "第二单元", Phonetic = "/tri:/" },
        new Vocab { Word = "long", Meaning = "长的", Book = "三年级下册", Unit = "第二单元", Phonetic = "/lɒŋ/, /lɔ:ŋ/" },
        new Vocab { Word = "small", Meaning = "小的", Book = "三年级下册", Unit = "第二单元", Phonetic = "/smɔ:l/" },
        new Vocab { Word = "elephant", Meaning = "大象", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'elɪfənt/" },
        new Vocab { Word = "panda", Meaning = "大熊猫", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'pændə/" },
        new Vocab { Word = "river", Meaning = "河；江", Book = "三年级下册", Unit = "第二单元", Phonetic = "/'rɪvə(r)/" },

        // 三年级下册 第三单元
        new Vocab { Word = "I", Meaning = "我", Book = "三年级下册", Unit = "第三单元", Phonetic = "/aɪ/" },
        new Vocab { Word = "like", Meaning = "像……那样", Book = "三年级下册", Unit = "第三单元", Phonetic = "/laɪk/" },
        new Vocab { Word = "chicken", Meaning = "鸡肉", Book = "三年级下册", Unit = "第三单元", Phonetic = "/'tʃɪkɪn/" },
        new Vocab { Word = "egg", Meaning = "蛋", Book = "三年级下册", Unit = "第三单元", Phonetic = "/eg/" },
        new Vocab { Word = "rice", Meaning = "米饭", Book = "三年级下册", Unit = "第三单元", Phonetic = "/raɪs/" },
        new Vocab { Word = "vegetable", Meaning = "蔬菜", Book = "三年级下册", Unit = "第三单元", Phonetic = "/'vedʒtəbl/" },
        new Vocab { Word = "juice", Meaning = "果汁", Book = "三年级下册", Unit = "第三单元", Phonetic = "/dʒu:s/" },
        new Vocab { Word = "milk", Meaning = "牛奶", Book = "三年级下册", Unit = "第三单元", Phonetic = "/mɪlk/" },
        new Vocab { Word = "bread", Meaning = "面包", Book = "三年级下册", Unit = "第三单元", Phonetic = "/bred/" },
        new Vocab { Word = "fruit", Meaning = "水果", Book = "三年级下册", Unit = "第三单元", Phonetic = "/fru:t/" },
        new Vocab { Word = "drink", Meaning = "喝；饮", Book = "三年级下册", Unit = "第三单元", Phonetic = "/drɪŋk/" },
        new Vocab { Word = "soup", Meaning = "汤", Book = "三年级下册", Unit = "第三单元", Phonetic = "/su:p/" },
        new Vocab { Word = "good", Meaning = "好的", Book = "三年级下册", Unit = "第三单元", Phonetic = "/gʊd/" },
        new Vocab { Word = "food", Meaning = "食物", Book = "三年级下册", Unit = "第三单元", Phonetic = "/fu:d/" },
        new Vocab { Word = "eat", Meaning = "吃", Book = "三年级下册", Unit = "第三单元", Phonetic = "/i:t/" },
        new Vocab { Word = "noodle", Meaning = "n.面条", Book = "三年级下册", Unit = "第三单元", Phonetic = "/'nu:dl/" },

        // 三年级下册 第四单元
        new Vocab { Word = "apple", Meaning = "苹果", Book = "三年级下册", Unit = "第四单元", Phonetic = "/'æpl/" },
        new Vocab { Word = "orange", Meaning = "橙色；橙色的", Book = "三年级下册", Unit = "第四单元", Phonetic = "/'ɒrɪndʒ/, /'ɔ:rɪndʒ/" },
        new Vocab { Word = "thanks", Meaning = "感谢", Book = "三年级下册", Unit = "第四单元", Phonetic = "/θæŋks/" },
        new Vocab { Word = "eleven", Meaning = "十一", Book = "三年级下册", Unit = "第四单元", Phonetic = "/ɪ'levən/" },
        new Vocab { Word = "fifteen", Meaning = "十五", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,fɪf'ti:n/" },
        new Vocab { Word = "fourteen", Meaning = "十四", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,fɔ:'ti:n/" },
        new Vocab { Word = "thirteen", Meaning = "十三", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,θɜ:(r)'ti:n/" },
        new Vocab { Word = "twelve", Meaning = "十二", Book = "三年级下册", Unit = "第四单元", Phonetic = "/twelv/" },
        new Vocab { Word = "twenty", Meaning = "二十", Book = "三年级下册", Unit = "第四单元", Phonetic = "/'twenti/" },
        new Vocab { Word = "welcome", Meaning = "欢迎", Book = "三年级下册", Unit = "第四单元", Phonetic = "/'welkəm/" },
        new Vocab { Word = "please", Meaning = "请", Book = "三年级下册", Unit = "第四单元", Phonetic = "/pli:z/" },
        new Vocab { Word = "ice cream", Meaning = "冰激凌", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,aɪs'kri:m/" },
        new Vocab { Word = "eighteen", Meaning = "十八", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,eɪ'ti:n/" },
        new Vocab { Word = "nineteen", Meaning = "十九", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,naɪn'ti:n/" },
        new Vocab { Word = "seventeen", Meaning = "十七", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,sevn'ti:n/" },
        new Vocab { Word = "sixteen", Meaning = "十六", Book = "三年级下册", Unit = "第四单元", Phonetic = "/,sɪks'ti:n/" },

        // 四年级上册 第一单元
        new Vocab { Word = "is", Meaning = "是（第三人称单数）", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ɪz/" },
        new Vocab { Word = "this", Meaning = "这；这个", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ðɪs/" },
        new Vocab { Word = "it", Meaning = "它", Book = "四年级上册", Unit = "第一单元", Phonetic = "/,aɪ 'ti:/" },
        new Vocab { Word = "are", Meaning = "是（复数；第二人称单数）", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ɑ:(r); ə(r)/" },
        new Vocab { Word = "dress", Meaning = "连衣裙", Book = "四年级上册", Unit = "第一单元", Phonetic = "/dres/" },
        new Vocab { Word = "shirt", Meaning = "（尤指男士）衬衫", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ʃɜ:(r)t/" },
        new Vocab { Word = "shorts", Meaning = "短裤", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ʃɔ:(r)ts/" },
        new Vocab { Word = "skirt", Meaning = "女裙", Book = "四年级上册", Unit = "第一单元", Phonetic = "/skɜ:(r)t/" },
        new Vocab { Word = "new", Meaning = "新的", Book = "四年级上册", Unit = "第一单元", Phonetic = "/nju:/" },
        new Vocab { Word = "today", Meaning = "今天", Book = "四年级上册", Unit = "第一单元", Phonetic = "/tə'deɪ/" },
        new Vocab { Word = "old", Meaning = "老的；年纪大的", Book = "四年级上册", Unit = "第一单元", Phonetic = "/əʊld/" },
        new Vocab { Word = "cap", Meaning = "帽子", Book = "四年级上册", Unit = "第一单元", Phonetic = "/kæp/" },
        new Vocab { Word = "coat", Meaning = "外衣；大衣", Book = "四年级上册", Unit = "第一单元", Phonetic = "/kəʊt/" },
        new Vocab { Word = "sweater", Meaning = "毛衣", Book = "四年级上册", Unit = "第一单元", Phonetic = "/'swetə(r)/" },
        new Vocab { Word = "trousers", Meaning = "裤子；长裤", Book = "四年级上册", Unit = "第一单元", Phonetic = "/'traʊzə(r)z/" },
        new Vocab { Word = "week", Meaning = "周", Book = "四年级上册", Unit = "第一单元", Phonetic = "/wi:k/" },
        new Vocab { Word = "they", Meaning = "他们", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ðeɪ/" },
        new Vocab { Word = "day", Meaning = "一天；一日", Book = "四年级上册", Unit = "第一单元", Phonetic = "/deɪ/" },
        new Vocab { Word = "not", Meaning = "不", Book = "四年级上册", Unit = "第一单元", Phonetic = "/nɒt/, /nɑ:t/" },
        new Vocab { Word = "these", Meaning = "（this的复数形式）这些", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ði:z/" },
        new Vocab { Word = "Miss", Meaning = "小姐", Book = "四年级上册", Unit = "第一单元", Phonetic = "/mɪs/" },
        new Vocab { Word = "shoe", Meaning = "鞋", Book = "四年级上册", Unit = "第一单元", Phonetic = "/ʃu:/" },
        new Vocab { Word = "sock", Meaning = "短袜", Book = "四年级上册", Unit = "第一单元", Phonetic = "/sɒk/, /sɑ:k/" },

        // 四年级上册 第二单元
        new Vocab { Word = "book", Meaning = "书", Book = "四年级上册", Unit = "第二单元", Phonetic = "/bʊk/" },
        new Vocab { Word = "face", Meaning = "脸", Book = "四年级上册", Unit = "第二单元", Phonetic = "/feɪs/" },
        new Vocab { Word = "my", Meaning = "我的", Book = "四年级上册", Unit = "第二单元", Phonetic = "/maɪ/" },
        new Vocab { Word = "do", Meaning = "做；干", Book = "四年级上册", Unit = "第二单元", Phonetic = "/du:, də/" },
        new Vocab { Word = "bed", Meaning = "床", Book = "四年级上册", Unit = "第二单元", Phonetic = "/bed/" },
        new Vocab { Word = "ball", Meaning = "球", Book = "四年级上册", Unit = "第二单元", Phonetic = "/bɔ:l/" },
        new Vocab { Word = "play with", Meaning = "与……玩耍", Book = "四年级上册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "toy", Meaning = "玩具", Book = "四年级上册", Unit = "第二单元", Phonetic = "/tɔɪ/" },
        new Vocab { Word = "with", Meaning = "和……一起", Book = "四年级上册", Unit = "第二单元", Phonetic = "/wɪð, wɪθ/" },
        new Vocab { Word = "kite", Meaning = "风筝", Book = "四年级上册", Unit = "第二单元", Phonetic = "/kaɪt/" },
        new Vocab { Word = "watch", Meaning = "看", Book = "四年级上册", Unit = "第二单元", Phonetic = "/wɒtʃ/, /wɑ:tʃ/" },
        new Vocab { Word = "TV", Meaning = "电视", Book = "四年级上册", Unit = "第二单元", Phonetic = "/,ti: 'vi:/" },
        new Vocab { Word = "listen", Meaning = "听", Book = "四年级上册", Unit = "第二单元", Phonetic = "/'lɪsn/" },
        new Vocab { Word = "play", Meaning = "踢；玩；参加（体育运动）", Book = "四年级上册", Unit = "第二单元", Phonetic = "/pleɪ/" },
        new Vocab { Word = "read", Meaning = "看；读", Book = "四年级上册", Unit = "第二单元", Phonetic = "/ri:d/" },
        new Vocab { Word = "fly", Meaning = "放（风筝等）", Book = "四年级上册", Unit = "第二单元", Phonetic = "/flaɪ/" },
        new Vocab { Word = "clean", Meaning = "打扫", Book = "四年级上册", Unit = "第二单元", Phonetic = "/kli:n/" },
        new Vocab { Word = "homework", Meaning = "作业", Book = "四年级上册", Unit = "第二单元", Phonetic = "/'həʊmwɜ:(r)k/" },
        new Vocab { Word = "wash", Meaning = "洗", Book = "四年级上册", Unit = "第二单元", Phonetic = "/wɒʃ/, /wɔ:ʃ/" },
        new Vocab { Word = "listen to", Meaning = "听（词组）", Book = "四年级上册", Unit = "第二单元", Phonetic = null },

        // 四年级上册 第三单元
        new Vocab { Word = "green", Meaning = "绿色；绿色的", Book = "四年级上册", Unit = "第三单元", Phonetic = "/gri:n/" },
        new Vocab { Word = "red", Meaning = "红色；红色的", Book = "四年级上册", Unit = "第三单元", Phonetic = "/red/" },
        new Vocab { Word = "yellow", Meaning = "黄色；黄色的", Book = "四年级上册", Unit = "第三单元", Phonetic = "/'jeləʊ/" },
        new Vocab { Word = "the", Meaning = "放在名词前，特指人、事或物", Book = "四年级上册", Unit = "第三单元", Phonetic = "/ði;ðə/" },
        new Vocab { Word = "where", Meaning = "哪里", Book = "四年级上册", Unit = "第三单元", Phonetic = "/weə(r)/, /wer/" },
        new Vocab { Word = "light", Meaning = "电灯", Book = "四年级上册", Unit = "第三单元", Phonetic = "/laɪt/" },
        new Vocab { Word = "near", Meaning = "距离近", Book = "四年级上册", Unit = "第三单元", Phonetic = "/nɪə/, /nɪr/" },
        new Vocab { Word = "car", Meaning = "小汽车", Book = "四年级上册", Unit = "第三单元", Phonetic = "/kɑ:(r)/" },
        new Vocab { Word = "school", Meaning = "学校", Book = "四年级上册", Unit = "第三单元", Phonetic = "/sku:l/" },
        new Vocab { Word = "thirty", Meaning = "三十", Book = "四年级上册", Unit = "第三单元", Phonetic = "/θɜ:(r)ti/" },
        new Vocab { Word = "classroom", Meaning = "教室", Book = "四年级上册", Unit = "第三单元", Phonetic = "/'klɑ:sru:m/, /'klæsru:m/" },
        new Vocab { Word = "library", Meaning = "图书馆", Book = "四年级上册", Unit = "第三单元", Phonetic = "/'laɪbrəri/, /'laɪbreri/" },
        new Vocab { Word = "playground", Meaning = "操场", Book = "四年级上册", Unit = "第三单元", Phonetic = "/'pleɪ,graʊnd/" },
        new Vocab { Word = "street", Meaning = "大街；街道", Book = "四年级上册", Unit = "第三单元", Phonetic = "/stri:t/" },
        new Vocab { Word = "bike", Meaning = "自行车；脚踏车", Book = "四年级上册", Unit = "第三单元", Phonetic = "/baɪk/" },
        new Vocab { Word = "bus", Meaning = "公共汽车", Book = "四年级上册", Unit = "第三单元", Phonetic = "/bʌs/" },
        new Vocab { Word = "taxi", Meaning = "出租汽车", Book = "四年级上册", Unit = "第三单元", Phonetic = "/'tæksi/" },
        new Vocab { Word = "from", Meaning = "从", Book = "四年级上册", Unit = "第三单元", Phonetic = "/frɒm/" },
        new Vocab { Word = "far", Meaning = "较远的", Book = "四年级上册", Unit = "第三单元", Phonetic = "/fɑ:(r)/" },
        new Vocab { Word = "far from", Meaning = "离......远", Book = "四年级上册", Unit = "第三单元", Phonetic = null },

        // 四年级上册 第四单元
        new Vocab { Word = "want", Meaning = "要；想要", Book = "四年级上册", Unit = "第四单元", Phonetic = "/wɒnt/, /wɑ:nt/" },
        new Vocab { Word = "park", Meaning = "公园", Book = "四年级上册", Unit = "第四单元", Phonetic = "/pɑ:(r)k/" },
        new Vocab { Word = "supermarket", Meaning = "超市", Book = "四年级上册", Unit = "第四单元", Phonetic = "/'su:pə(r),mɑ:(r)kət/" },
        new Vocab { Word = "go", Meaning = "去", Book = "四年级上册", Unit = "第四单元", Phonetic = "/gəʊ/" },
        new Vocab { Word = "to", Meaning = "向，朝", Book = "四年级上册", Unit = "第四单元", Phonetic = "/tu:; tə/" },
        new Vocab { Word = "let's", Meaning = "让我们……", Book = "四年级上册", Unit = "第四单元", Phonetic = null },
        new Vocab { Word = "potato", Meaning = "马铃薯；土豆", Book = "四年级上册", Unit = "第四单元", Phonetic = "/pə'teɪtəʊ/" },
        new Vocab { Word = "tomato", Meaning = "西红柿", Book = "四年级上册", Unit = "第四单元", Phonetic = "/tə'mɑ:təʊ/, /tə'meɪtəʊ/" },
        new Vocab { Word = "buy", Meaning = "买", Book = "四年级上册", Unit = "第四单元", Phonetic = "/baɪ/" },
        new Vocab { Word = "shop", Meaning = "商店", Book = "四年级上册", Unit = "第四单元", Phonetic = "/ʃɒp/, /ʃɑ:p/" },
        new Vocab { Word = "bag", Meaning = "包", Book = "四年级上册", Unit = "第四单元", Phonetic = "/bæg/" },
        new Vocab { Word = "go shopping", Meaning = "去买东西；购物（短语）", Book = "四年级上册", Unit = "第四单元", Phonetic = null },
        new Vocab { Word = "cinema", Meaning = "电影院", Book = "四年级上册", Unit = "第四单元", Phonetic = "/'sɪnəmə/" },
        new Vocab { Word = "way", Meaning = "方向", Book = "四年级上册", Unit = "第四单元", Phonetic = "/weɪ/" },

        // 四年级下册 第一单元
        new Vocab { Word = "pencil", Meaning = "铅笔", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'pensl/" },
        new Vocab { Word = "ruler", Meaning = "尺子", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'ru:lə(r)/" },
        new Vocab { Word = "schoolbag", Meaning = "书包", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'sku:lbæg/" },
        new Vocab { Word = "teacher", Meaning = "教师", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'ti:tʃə(r)/" },
        new Vocab { Word = "what", Meaning = "什么", Book = "四年级下册", Unit = "第一单元", Phonetic = "/wɒt/, /wɑ:t/" },
        new Vocab { Word = "you", Meaning = "你；你们", Book = "四年级下册", Unit = "第一单元", Phonetic = "/ju:/" },
        new Vocab { Word = "blackboard", Meaning = "黑板", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'blækbɔ:(r)d/" },
        new Vocab { Word = "chair", Meaning = "椅子", Book = "四年级下册", Unit = "第一单元", Phonetic = "/tʃeə(r)/, /tʃer/" },
        new Vocab { Word = "desk", Meaning = "书桌", Book = "四年级下册", Unit = "第一单元", Phonetic = "/desk/" },
        new Vocab { Word = "behind", Meaning = "在（或向）……后面", Book = "四年级下册", Unit = "第一单元", Phonetic = "/bɪ'haɪnd/" },
        new Vocab { Word = "your", Meaning = "你（们）的", Book = "四年级下册", Unit = "第一单元", Phonetic = "/jɔ:(r)/" },
        new Vocab { Word = "he", Meaning = "他", Book = "四年级下册", Unit = "第一单元", Phonetic = "/hi:/" },
        new Vocab { Word = "she", Meaning = "她", Book = "四年级下册", Unit = "第一单元", Phonetic = "/ʃi:/" },
        new Vocab { Word = "friend", Meaning = "朋友", Book = "四年级下册", Unit = "第一单元", Phonetic = "/frend/" },
        new Vocab { Word = "her", Meaning = "她的", Book = "四年级下册", Unit = "第一单元", Phonetic = "/hɜ:(r)/" },
        new Vocab { Word = "his", Meaning = "他的", Book = "四年级下册", Unit = "第一单元", Phonetic = "/hɪz/" },
        new Vocab { Word = "name", Meaning = "名字", Book = "四年级下册", Unit = "第一单元", Phonetic = "/neɪm/" },
        new Vocab { Word = "fifty", Meaning = "五十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'fɪfti/" },
        new Vocab { Word = "forty", Meaning = "四十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'fɔ:(r)ti/" },
        new Vocab { Word = "crayon", Meaning = "蜡笔", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'kreɪən/" },
        new Vocab { Word = "pen", Meaning = "钢笔", Book = "四年级下册", Unit = "第一单元", Phonetic = "/pen/" },
        new Vocab { Word = "between", Meaning = "在……中间", Book = "四年级下册", Unit = "第一单元", Phonetic = "/bɪ'twi:n/" },
        new Vocab { Word = "pencil box", Meaning = "铅笔盒", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'pensl ,bɒks/" },
        new Vocab { Word = "pupil", Meaning = "学生；（尤指）小学生", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'pju:pl/" },
        new Vocab { Word = "eighty", Meaning = "八十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'eɪti/" },
        new Vocab { Word = "ninety", Meaning = "九十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'naɪnti/" },
        new Vocab { Word = "seventy", Meaning = "七十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'sevnti/" },
        new Vocab { Word = "sixty", Meaning = "六十", Book = "四年级下册", Unit = "第一单元", Phonetic = "/'sɪksti/" },
        new Vocab { Word = "hello", Meaning = "喂；你好（招呼用语）", Book = "四年级下册", Unit = "第一单元", Phonetic = "/hə'ləʊ/" },
        new Vocab { Word = "hi", Meaning = "喂；嗨（招呼用户）", Book = "四年级下册", Unit = "第一单元", Phonetic = "/haɪ/" },
        new Vocab { Word = "whose", Meaning = "谁的", Book = "四年级下册", Unit = "第一单元", Phonetic = "/hu:z/" },
        new Vocab { Word = "beside", Meaning = "在旁边（附近）", Book = "四年级下册", Unit = "第一单元", Phonetic = "/bɪ'saɪd/" },

        // 四年级下册 第二单元
        new Vocab { Word = "how", Meaning = "多少", Book = "四年级下册", Unit = "第二单元", Phonetic = "/haʊ/" },
        new Vocab { Word = "cloudy", Meaning = "阴天的；多云的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/'klaʊdi/" },
        new Vocab { Word = "sunny", Meaning = "阳光充足的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/'sʌni/" },
        new Vocab { Word = "windy", Meaning = "多风的；风大的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/'wɪndi/" },
        new Vocab { Word = "weather", Meaning = "天气", Book = "四年级下册", Unit = "第二单元", Phonetic = "/'weðə(r)/" },
        new Vocab { Word = "cold", Meaning = "寒冷的；冷的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/kəʊld/" },
        new Vocab { Word = "cool", Meaning = "凉的；凉爽的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/ku:l/" },
        new Vocab { Word = "hot", Meaning = "热的；烫的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/hɒt/, /hɑ:t/" },
        new Vocab { Word = "warm", Meaning = "温暖的；暖和的", Book = "四年级下册", Unit = "第二单元", Phonetic = "/wɔ:(r)m/" },
        new Vocab { Word = "May", Meaning = "五月", Book = "四年级下册", Unit = "第二单元", Phonetic = "/meɪ/" },
        new Vocab { Word = "snow", Meaning = "雪", Book = "四年级下册", Unit = "第二单元", Phonetic = "/snəʊ/" },
        new Vocab { Word = "month", Meaning = "月", Book = "四年级下册", Unit = "第二单元", Phonetic = "/mʌnθ/" },
        new Vocab { Word = "rain", Meaning = "雨；下雨", Book = "四年级下册", Unit = "第二单元", Phonetic = "/reɪn/" },
        new Vocab { Word = "sun", Meaning = "太阳", Book = "四年级下册", Unit = "第二单元", Phonetic = "/sʌn/" },
        new Vocab { Word = "Apr.", Meaning = "Apr. 四月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Aug.", Meaning = "Aug. 八月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Dec.", Meaning = "Dec. 十二月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Feb.", Meaning = "Feb. 二月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Jan.", Meaning = "Jan. 一月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Jul.", Meaning = "Jul. 七月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Jun.", Meaning = "Jun. 六月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Mar.", Meaning = "Mar. 三月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Nov.", Meaning = "Nov. 十一月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Oct.", Meaning = "Oct. 十月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },
        new Vocab { Word = "Sept.", Meaning = "Sept. 九月（缩写）", Book = "四年级下册", Unit = "第二单元", Phonetic = null },

        // 四年级下册 第三单元
        new Vocab { Word = "tall", Meaning = "高的", Book = "四年级下册", Unit = "第三单元", Phonetic = "/tɔ:l/" },
        new Vocab { Word = "too", Meaning = "太；过于", Book = "四年级下册", Unit = "第三单元", Phonetic = "/tu:/" },
        new Vocab { Word = "when", Meaning = "什么时候；何时", Book = "四年级下册", Unit = "第三单元", Phonetic = "/wen/" },
        new Vocab { Word = "foot", Meaning = "脚", Book = "四年级下册", Unit = "第三单元", Phonetic = "/fʊt/" },
        new Vocab { Word = "birthday", Meaning = "生日", Book = "四年级下册", Unit = "第三单元", Phonetic = "/'bɜ:(r)θdeɪ/" },
        new Vocab { Word = "on foot", Meaning = "步行", Book = "四年级下册", Unit = "第三单元", Phonetic = null },
        new Vocab { Word = "live", Meaning = "居住", Book = "四年级下册", Unit = "第三单元", Phonetic = "/lɪv/" },
        new Vocab { Word = "am", Meaning = "是（第一人称单数）", Book = "四年级下册", Unit = "第三单元", Phonetic = "/æm/" },
        new Vocab { Word = "by", Meaning = "在……之前", Book = "四年级下册", Unit = "第三单元", Phonetic = "/baɪ/" },

        // 四年级下册 第四单元
        new Vocab { Word = "blue", Meaning = "蓝色；蓝色的", Book = "四年级下册", Unit = "第四单元", Phonetic = "/blu:/" },
        new Vocab { Word = "colour", Meaning = "颜色", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'kʌlə/" },
        new Vocab { Word = "and", Meaning = "和；与", Book = "四年级下册", Unit = "第四单元", Phonetic = "/ænd; ənd/" },
        new Vocab { Word = "favourite", Meaning = "特别喜爱的", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'feɪvərət/" },
        new Vocab { Word = "Chinese", Meaning = "中文", Book = "四年级下册", Unit = "第四单元", Phonetic = "/tʃaɪ'ni:z/" },
        new Vocab { Word = "English", Meaning = "英语", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'ɪŋglɪʃ/" },
        new Vocab { Word = "PE", Meaning = "体育", Book = "四年级下册", Unit = "第四单元", Phonetic = "/,pi: 'i:/" },
        new Vocab { Word = "science", Meaning = "科学", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'saɪəns/" },
        new Vocab { Word = "art", Meaning = "美术", Book = "四年级下册", Unit = "第四单元", Phonetic = "/ɑ:(r)t/" },
        new Vocab { Word = "music", Meaning = "音乐", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'mju:zɪk/" },
        new Vocab { Word = "our", Meaning = "我们的", Book = "四年级下册", Unit = "第四单元", Phonetic = "/ɑ:(r), 'aʊə(r)/" },
        new Vocab { Word = "their", Meaning = "他们的；她们的；它们的", Book = "四年级下册", Unit = "第四单元", Phonetic = "/ðeə(r)/, /ðer/" },
        new Vocab { Word = "but", Meaning = "但是", Book = "四年级下册", Unit = "第四单元", Phonetic = "/bʌt; bət/" },
        new Vocab { Word = "subject", Meaning = "科目；学科", Book = "四年级下册", Unit = "第四单元", Phonetic = "/'sʌbdʒɪkt/" },
        new Vocab { Word = "brown", Meaning = "棕色；棕色的", Book = "四年级下册", Unit = "第四单元", Phonetic = "/braʊn/" },
        new Vocab { Word = "clothes", Meaning = "衣服；服装", Book = "四年级下册", Unit = "第四单元", Phonetic = "/kləʊðz, kləʊz/" },
        new Vocab { Word = "math", Meaning = "n.数学", Book = "四年级下册", Unit = "第四单元", Phonetic = "/mæθ/" },

        // 五年级上册 第一单元 My Family（补充音标）
        new Vocab { Word = "father", Meaning = "父亲；爸爸", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'fɑ:ðə(r)/" },
        new Vocab { Word = "mother", Meaning = "母亲；妈妈", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'mʌðə(r)/" },
        new Vocab { Word = "grandfather", Meaning = "（外）祖父", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'grænfɑ:ðə(r)/" },
        new Vocab { Word = "grandmother", Meaning = "（外）祖母", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'grænmʌðə(r)/" },
        new Vocab { Word = "have", Meaning = "有；吃；进行（活动）", Book = "五年级上册", Unit = "第一单元", Phonetic = "/hæv; həv/" },
        new Vocab { Word = "brother", Meaning = "兄；弟", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'brʌðə(r)/" },
        new Vocab { Word = "sister", Meaning = "姐；妹", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'sɪstə(r)/" },
        new Vocab { Word = "parent", Meaning = "父（母）亲", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'peərənt/" },
        new Vocab { Word = "white", Meaning = "白色；白色的", Book = "五年级上册", Unit = "第一单元", Phonetic = "/waɪt/" },
        new Vocab { Word = "hair", Meaning = "头发；毛发", Book = "五年级上册", Unit = "第一单元", Phonetic = "/heə/, /her/" },
        new Vocab { Word = "black", Meaning = "黑色；黑色的", Book = "五年级上册", Unit = "第一单元", Phonetic = "/blæk/" },
        new Vocab { Word = "uncle", Meaning = "叔；伯；舅；姑夫；姨父", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'ʌŋkl/" },
        new Vocab { Word = "aunt", Meaning = "伯母；舅母；婶；姑；姨", Book = "五年级上册", Unit = "第一单元", Phonetic = "/ɑ:nt/, /ænt/" },
        new Vocab { Word = "cousin", Meaning = "堂（表）兄弟；堂（表）姐妹", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'kʌzn/" },
        new Vocab { Word = "thin", Meaning = "瘦的", Book = "五年级上册", Unit = "第一单元", Phonetic = "/θɪn/" },
        new Vocab { Word = "work", Meaning = "工作；劳动", Book = "五年级上册", Unit = "第一单元", Phonetic = "/wɜ:(r)k/" },
        new Vocab { Word = "doctor", Meaning = "医生", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'dɒktə(r)/" },
        new Vocab { Word = "hospital", Meaning = "医院", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'hɒspɪtl/, /'hɑ:spɪtl/" },
        new Vocab { Word = "nurse", Meaning = "护士", Book = "五年级上册", Unit = "第一单元", Phonetic = "/nɜ:(r)s/" },
        new Vocab { Word = "worker", Meaning = "工人", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'wɜ:(r)kə(r)/" },
        new Vocab { Word = "walk", Meaning = "步行；散步", Book = "五年级上册", Unit = "第一单元", Phonetic = "/wɔ:k/" },
        new Vocab { Word = "go for a walk", Meaning = "去散步", Book = "五年级上册", Unit = "第一单元", Phonetic = "/gəʊ fə(r) ə wɔ:k/" },
        new Vocab { Word = "plant", Meaning = "种植；植物", Book = "五年级上册", Unit = "第一单元", Phonetic = "/plɑ:nt/, /plænt/" },
        new Vocab { Word = "flower", Meaning = "花；花朵", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'flaʊə(r)/" },
        new Vocab { Word = "cook", Meaning = "烹调；厨师", Book = "五年级上册", Unit = "第一单元", Phonetic = "/kʊk/" },
        new Vocab { Word = "we", Meaning = "我们", Book = "五年级上册", Unit = "第一单元", Phonetic = "/wi:/" },
        new Vocab { Word = "family", Meaning = "家；家庭", Book = "五年级上册", Unit = "第一单元", Phonetic = "/'fæməli/" },
        new Vocab { Word = "film", Meaning = "电影；影片", Book = "五年级上册", Unit = "第一单元", Phonetic = "/fɪlm/" },
        new Vocab { Word = "watch a film", Meaning = "看电影", Book = "五年级上册", Unit = "第一单元", Phonetic = "/wɒtʃ ə fɪlm/" },

        // 五年级上册 第二单元 My Country and English-speaking Countries（补充音标）
        new Vocab { Word = "China", Meaning = "中国", Book = "五年级上册", Unit = "第二单元", Phonetic = "/'tʃaɪnə/" },
        new Vocab { Word = "map", Meaning = "地图", Book = "五年级上册", Unit = "第二单元", Phonetic = "/mæp/" },
        new Vocab { Word = "speak", Meaning = "说；讲", Book = "五年级上册", Unit = "第二单元", Phonetic = "/spi:k/" },
        new Vocab { Word = "know", Meaning = "知道；了解", Book = "五年级上册", Unit = "第二单元", Phonetic = "/nəʊ/" },
        new Vocab { Word = "about", Meaning = "关于；大约", Book = "五年级上册", Unit = "第二单元", Phonetic = "/ə'baʊt/" },
        new Vocab { Word = "city", Meaning = "城市", Book = "五年级上册", Unit = "第二单元", Phonetic = "/'sɪti/" },
        new Vocab { Word = "of", Meaning = "…… 的（表示所属）", Book = "五年级上册", Unit = "第二单元", Phonetic = "/ɒv; əv/, /ʌv; əv/" },
        new Vocab { Word = "star", Meaning = "星；恒星", Book = "五年级上册", Unit = "第二单元", Phonetic = "/stɑ:(r)/" },
        new Vocab { Word = "here", Meaning = "这里；在这儿", Book = "五年级上册", Unit = "第二单元", Phonetic = "/hɪə(r)/, /hɪr/" },
        new Vocab { Word = "beautiful", Meaning = "美丽的；漂亮的", Book = "五年级上册", Unit = "第二单元", Phonetic = "/'bju:tɪfl/" },

        // 五年级上册 第三单元 A Travel Plan（补充音标）
        new Vocab { Word = "love", Meaning = "爱；喜欢", Book = "五年级上册", Unit = "第三单元", Phonetic = "/lʌv/" },
        new Vocab { Word = "travel", Meaning = "旅行", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'trævl/" },
        new Vocab { Word = "interesting", Meaning = "有趣的；有意思的", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'ɪntrəstɪŋ/" },
        new Vocab { Word = "place", Meaning = "地方；场所", Book = "五年级上册", Unit = "第三单元", Phonetic = "/pleɪs/" },
        new Vocab { Word = "may", Meaning = "可以；也许", Book = "五年级上册", Unit = "第三单元", Phonetic = "/meɪ/" },
        new Vocab { Word = "young", Meaning = "年轻的；幼小的", Book = "五年级上册", Unit = "第三单元", Phonetic = "/jʌŋ/" },
        new Vocab { Word = "come", Meaning = "来；来到", Book = "五年级上册", Unit = "第三单元", Phonetic = "/kʌm/" },
        new Vocab { Word = "great", Meaning = "伟大的；极好的", Book = "五年级上册", Unit = "第三单元", Phonetic = "/greɪt/" },
        new Vocab { Word = "call", Meaning = "打电话；称呼", Book = "五年级上册", Unit = "第三单元", Phonetic = "/kɔ:l/" },
        new Vocab { Word = "slow", Meaning = "慢的；缓慢的", Book = "五年级上册", Unit = "第三单元", Phonetic = "/sləʊ/" },
        new Vocab { Word = "plane", Meaning = "飞机", Book = "五年级上册", Unit = "第三单元", Phonetic = "/pleɪn/" },
        new Vocab { Word = "fast", Meaning = "快的；迅速的", Book = "五年级上册", Unit = "第三单元", Phonetic = "/fɑ:st/, /fæst/" },
        new Vocab { Word = "train", Meaning = "火车", Book = "五年级上册", Unit = "第三单元", Phonetic = "/treɪn/" },
        new Vocab { Word = "from … to …", Meaning = "从…… 到……", Book = "五年级上册", Unit = "第三单元", Phonetic = null },
        new Vocab { Word = "Sunday", Meaning = "星期日", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'sʌndeɪ/" },
        new Vocab { Word = "Monday", Meaning = "星期一", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'mʌndeɪ/" },
        new Vocab { Word = "Tuesday", Meaning = "星期二", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'tju:zdeɪ/, /'tu:zdeɪ/" },
        new Vocab { Word = "Wednesday", Meaning = "星期三", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'wenzdeɪ/" },
        new Vocab { Word = "Thursday", Meaning = "星期四", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'θɜ:(r)zdeɪ/" },
        new Vocab { Word = "Friday", Meaning = "星期五", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'fraɪdeɪ/" },
        new Vocab { Word = "Saturday", Meaning = "星期六", Book = "五年级上册", Unit = "第三单元", Phonetic = "/'sætə(r)deɪ/" },

        // 五年级上册 第四单元 Shopping in the City（补充音标）
        new Vocab { Word = "at", Meaning = "在（某处或某时间）", Book = "五年级上册", Unit = "第四单元", Phonetic = "/æt/" },
        new Vocab { Word = "evening", Meaning = "晚上；傍晚", Book = "五年级上册", Unit = "第四单元", Phonetic = "/'i:vnɪŋ/" },
        new Vocab { Word = "nice", Meaning = "令人愉快的；好的", Book = "五年级上册", Unit = "第四单元", Phonetic = "/naɪs/" },
        new Vocab { Word = "meet", Meaning = "相遇；遇见", Book = "五年级上册", Unit = "第四单元", Phonetic = "/mi:t/" },
        new Vocab { Word = "morning", Meaning = "早晨；上午", Book = "五年级上册", Unit = "第四单元", Phonetic = "/'mɔ:(r)nɪŋ/" },
        new Vocab { Word = "afternoon", Meaning = "下午", Book = "五年级上册", Unit = "第四单元", Phonetic = "/,ɑ:ftə'nu:n/, /,æftər'nu:n/" },
        new Vocab { Word = "room", Meaning = "房间；空间", Book = "五年级上册", Unit = "第四单元", Phonetic = "/ru:m/" },
        new Vocab { Word = "door", Meaning = "门", Book = "五年级上册", Unit = "第四单元", Phonetic = "/dɔ:(r)/" },
        new Vocab { Word = "window", Meaning = "窗户", Book = "五年级上册", Unit = "第四单元", Phonetic = "/'wɪndəʊ/" },
        new Vocab { Word = "make", Meaning = "做；制造", Book = "五年级上册", Unit = "第四单元", Phonetic = "/meɪk/" },
        new Vocab { Word = "kid", Meaning = "小孩；小家伙", Book = "五年级上册", Unit = "第四单元", Phonetic = "/kɪd/" },
        new Vocab { Word = "year", Meaning = "年；岁", Book = "五年级上册", Unit = "第四单元", Phonetic = "/jɪə/, /jɪr/" },
        new Vocab { Word = "also", Meaning = "而且；也", Book = "五年级上册", Unit = "第四单元", Phonetic = "/'ɔ:lsəʊ/" },
        new Vocab { Word = "boat", Meaning = "船；小船", Book = "五年级上册", Unit = "第四单元", Phonetic = "/bəʊt/" },
        new Vocab { Word = "moon", Meaning = "月亮；月球", Book = "五年级上册", Unit = "第四单元", Phonetic = "/mu:n/" },
        new Vocab { Word = "wonderful", Meaning = "奇妙的；极好的", Book = "五年级上册", Unit = "第四单元", Phonetic = "/'wʌndə(r)fl/" },
        new Vocab { Word = "those", Meaning = "那些", Book = "五年级上册", Unit = "第四单元", Phonetic = "/ðəʊz/" },
        new Vocab { Word = "that", Meaning = "那；那个", Book = "五年级上册", Unit = "第四单元", Phonetic = "/ðæt/" },

        // 五年级下册 第一单元（补充音标）
        new Vocab { Word = "run", Meaning = "跑", Book = "五年级下册", Unit = "第一单元", Phonetic = "/rʌn/" },
        new Vocab { Word = "sorry", Meaning = "对不起，不好意思（道歉时用）", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'sɒri/" },
        new Vocab { Word = "jump", Meaning = "跳；跳跃", Book = "五年级下册", Unit = "第一单元", Phonetic = "/dʒʌmp/" },
        new Vocab { Word = "sing", Meaning = "唱；演唱", Book = "五年级下册", Unit = "第一单元", Phonetic = "/sɪŋ/" },
        new Vocab { Word = "dance", Meaning = "跳舞", Book = "五年级下册", Unit = "第一单元", Phonetic = "/dɑ:ns/, /dæns/" },
        new Vocab { Word = "sit", Meaning = "坐", Book = "五年级下册", Unit = "第一单元", Phonetic = "/sɪt/" },
        new Vocab { Word = "down", Meaning = "向下；朝下；沿着", Book = "五年级下册", Unit = "第一单元", Phonetic = "/daʊn/" },
        new Vocab { Word = "stand", Meaning = "站立；直立", Book = "五年级下册", Unit = "第一单元", Phonetic = "/stænd/" },
        new Vocab { Word = "up", Meaning = "向上；在上面", Book = "五年级下册", Unit = "第一单元", Phonetic = "/ʌp/" },
        new Vocab { Word = "see", Meaning = "看见；明白；会见（过去式为 saw）", Book = "五年级下册", Unit = "第一单元", Phonetic = "/si:/" },
        new Vocab { Word = "look", Meaning = "看；瞧", Book = "五年级下册", Unit = "第一单元", Phonetic = "/lʊk/" },
        new Vocab { Word = "boy", Meaning = "男孩", Book = "五年级下册", Unit = "第一单元", Phonetic = "/bɔɪ/" },
        new Vocab { Word = "girl", Meaning = "女孩", Book = "五年级下册", Unit = "第一单元", Phonetic = "/gɜ:(r)l/" },
        new Vocab { Word = "now", Meaning = "现在", Book = "五年级下册", Unit = "第一单元", Phonetic = "/naʊ/" },
        new Vocab { Word = "draw", Meaning = "画", Book = "五年级下册", Unit = "第一单元", Phonetic = "/drɔ:/" },
        new Vocab { Word = "picture", Meaning = "图画；照片", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'pɪktʃə(r)/" },
        new Vocab { Word = "woman", Meaning = "女人", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'wʊmən/" },
        new Vocab { Word = "baby", Meaning = "婴儿", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'beɪbi/" },
        new Vocab { Word = "cry", Meaning = "哭；哭泣；喊叫", Book = "五年级下册", Unit = "第一单元", Phonetic = "/kraɪ/" },
        new Vocab { Word = "talk", Meaning = "交谈；讨论", Book = "五年级下册", Unit = "第一单元", Phonetic = "/tɔ:k/" },
        new Vocab { Word = "man", Meaning = "男人", Book = "五年级下册", Unit = "第一单元", Phonetic = "/mæn/" },
        new Vocab { Word = "sleep", Meaning = "睡觉；入睡", Book = "五年级下册", Unit = "第一单元", Phonetic = "/sli:p/" },
        new Vocab { Word = "who", Meaning = "谁", Book = "五年级下册", Unit = "第一单元", Phonetic = "/hu:/" },
        new Vocab { Word = "hungry", Meaning = "饥饿的", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'hʌŋgri/" },
        new Vocab { Word = "water", Meaning = "水", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'wɔ:tə/, /'wɑ:tər/" },
        new Vocab { Word = "tea", Meaning = "茶", Book = "五年级下册", Unit = "第一单元", Phonetic = "/ti:/" },
        new Vocab { Word = "candy", Meaning = "糖果", Book = "五年级下册", Unit = "第一单元", Phonetic = "/'kændi/" },

        // 五年级下册 第二单元（补充音标）
        new Vocab { Word = "people", Meaning = "人们", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'pi:pl/" },
        new Vocab { Word = "many", Meaning = "许多的；许多", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'meni/" },
        new Vocab { Word = "child", Meaning = "孩子（复数形式为 children）", Book = "五年级下册", Unit = "第二单元", Phonetic = "/tʃaɪld/" },
        new Vocab { Word = "women", Meaning = "女人（woman 的复数形式）", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'wɪmɪn/" },
        new Vocab { Word = "men", Meaning = "男人（man 的复数形式）", Book = "五年级下册", Unit = "第二单元", Phonetic = "/men/" },
        new Vocab { Word = "say", Meaning = "说", Book = "五年级下册", Unit = "第二单元", Phonetic = "/seɪ/" },
        new Vocab { Word = "help", Meaning = "救命；帮助", Book = "五年级下册", Unit = "第二单元", Phonetic = "/help/" },
        new Vocab { Word = "worry", Meaning = "担心；担忧", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'wʌri/, /'wɜ:ri/" },
        new Vocab { Word = "sad", Meaning = "悲伤的", Book = "五年级下册", Unit = "第二单元", Phonetic = "/sæd/" },
        new Vocab { Word = "take", Meaning = "乘坐；买下；拍照", Book = "五年级下册", Unit = "第二单元", Phonetic = "/teɪk/" },
        new Vocab { Word = "take a picture", Meaning = "拍照", Book = "五年级下册", Unit = "第二单元", Phonetic = "/teɪk ə 'pɪktʃə(r)/" },
        new Vocab { Word = "be", Meaning = "是；存在（am, is, are 等的原形动词）", Book = "五年级下册", Unit = "第二单元", Phonetic = "/bi:, bi/" },
        new Vocab { Word = "feel", Meaning = "觉得；感到", Book = "五年级下册", Unit = "第二单元", Phonetic = "/fi:l/" },
        new Vocab { Word = "tired", Meaning = "疲劳的；累的", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'taɪə(r)d/" },
        new Vocab { Word = "stop", Meaning = "停下，停止；（公共汽车、火车）站", Book = "五年级下册", Unit = "第二单元", Phonetic = "/stɒp/, /stɑ:p/" },
        new Vocab { Word = "wait", Meaning = "等待", Book = "五年级下册", Unit = "第二单元", Phonetic = "/weɪt/" },
        new Vocab { Word = "afraid", Meaning = "害怕，畏惧", Book = "五年级下册", Unit = "第二单元", Phonetic = "/ə'freɪd/" },
        new Vocab { Word = "for", Meaning = "为……；给……", Book = "五年级下册", Unit = "第二单元", Phonetic = "/fɔ:(r); fə(r)/" },
        new Vocab { Word = "busy", Meaning = "忙碌的", Book = "五年级下册", Unit = "第二单元", Phonetic = "/'bɪzi/" },

        // 五年级下册 第三单元（补充音标）
        new Vocab { Word = "much", Meaning = "（与 how 连用以询问数量）多少；很；非常", Book = "五年级下册", Unit = "第三单元", Phonetic = "/mʌtʃ/" },
        new Vocab { Word = "write", Meaning = "写", Book = "五年级下册", Unit = "第三单元", Phonetic = "/raɪt/" },
        new Vocab { Word = "mum", Meaning = "妈妈（非正式用语）", Book = "五年级下册", Unit = "第三单元", Phonetic = "/mʌm/" },
        new Vocab { Word = "dad", Meaning = "爸爸（非正式用语）", Book = "五年级下册", Unit = "第三单元", Phonetic = "/dæd/" },
        new Vocab { Word = "dear", Meaning = "亲爱的", Book = "五年级下册", Unit = "第三单元", Phonetic = "/dɪə(r)/" },
        new Vocab { Word = "fine", Meaning = "健康的；晴朗的", Book = "五年级下册", Unit = "第三单元", Phonetic = "/faɪn/" },
        new Vocab { Word = "left", Meaning = "左边的；左边", Book = "五年级下册", Unit = "第三单元", Phonetic = "/left/" },
        new Vocab { Word = "right", Meaning = "右边的；右边", Book = "五年级下册", Unit = "第三单元", Phonetic = "/raɪt/" },
        new Vocab { Word = "turn", Meaning = "转向；转弯", Book = "五年级下册", Unit = "第三单元", Phonetic = "/tɜ:(r)n/" },
        new Vocab { Word = "wrong", Meaning = "错误的", Book = "五年级下册", Unit = "第三单元", Phonetic = "/rɒŋ/, /rɔ:ŋ/" },
        new Vocab { Word = "email", Meaning = "电子邮件", Book = "五年级下册", Unit = "第三单元", Phonetic = "/'i:meɪl/" },
        new Vocab { Word = "idea", Meaning = "想法；主意", Book = "五年级下册", Unit = "第三单元", Phonetic = "/aɪ'dɪə/, /aɪ'dɪr/" },
        new Vocab { Word = "computer", Meaning = "电脑", Book = "五年级下册", Unit = "第三单元", Phonetic = "/kəm'pju:tə(r)/" },
        new Vocab { Word = "use", Meaning = "使用；利用", Book = "五年级下册", Unit = "第三单元", Phonetic = "/ju:z/" },
        new Vocab { Word = "kind", Meaning = "友好的；体贴的", Book = "五年级下册", Unit = "第三单元", Phonetic = "/kaɪnd/" },
        new Vocab { Word = "us", Meaning = "我们（we 的宾格形式）", Book = "五年级下册", Unit = "第三单元", Phonetic = "/,ju: 'es/" },

        // 五年级下册 第四单元（补充音标）
        new Vocab { Word = "story", Meaning = "故事", Book = "五年级下册", Unit = "第四单元", Phonetic = "/'stɔ:ri/" },
        new Vocab { Word = "did", Meaning = "做，干；助动词（do 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/dɪd/" },
        new Vocab { Word = "yesterday", Meaning = "昨天", Book = "五年级下册", Unit = "第四单元", Phonetic = "/'jestə(r)di/" },
        new Vocab { Word = "night", Meaning = "夜晚，晚上", Book = "五年级下册", Unit = "第四单元", Phonetic = "/naɪt/" },
        new Vocab { Word = "had", Meaning = "有；吃；进行（活动）（have 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/hæd/" },
        new Vocab { Word = "went", Meaning = "去；走；离开（go 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/went/" },
        new Vocab { Word = "saw", Meaning = "看见（see 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/sɔ:/" },
        new Vocab { Word = "ate", Meaning = "吃（eat 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/eɪt/" },
        new Vocab { Word = "photo", Meaning = "照片", Book = "五年级下册", Unit = "第四单元", Phonetic = "/'fəʊtəʊ/" },
        new Vocab { Word = "were", Meaning = "是；存在（are 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/wɜ:(r); wə(r)/" },
        new Vocab { Word = "was", Meaning = "是；存在（am, is 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/wɒz; wəz/" },
        new Vocab { Word = "happy", Meaning = "快乐的；高兴的", Book = "五年级下册", Unit = "第四单元", Phonetic = "/'hæpi/" },
        new Vocab { Word = "bought", Meaning = "买（buy 的过去式）", Book = "五年级下册", Unit = "第四单元", Phonetic = "/bɔ:t/" },
        new Vocab { Word = "back", Meaning = "回原处；向后", Book = "五年级下册", Unit = "第四单元", Phonetic = "/bæk/" },

        // 六年级上册 第一单元 （已修正）
        new Vocab { Word = "there", Meaning = "在那里;（表示存在或发生）", Book = "六年级上册", Unit = "第一单元", Phonetic = "/ðeə(r)/, /ðer/" },
        new Vocab { Word = "card", Meaning = "纸牌、卡片", Book = "六年级上册", Unit = "第一单元", Phonetic = "/kɑ:(r)d/" },
        new Vocab { Word = "time", Meaning = "时间", Book = "六年级上册", Unit = "第一单元", Phonetic = "/taɪm/" },
        new Vocab { Word = "floor", Meaning = "地板", Book = "六年级上册", Unit = "第一单元", Phonetic = "/flɔ:(r)/" },
        new Vocab { Word = "toilet", Meaning = "卫生间、厕所、坐便器", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'tɔɪlət/" },
        new Vocab { Word = "home", Meaning = "家", Book = "六年级上册", Unit = "第一单元", Phonetic = "/həʊm/" },
        new Vocab { Word = "kitchen", Meaning = "厨房", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'kɪtʃɪn/" },
        new Vocab { Word = "study", Meaning = "书房", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'stʌdi/" },
        new Vocab { Word = "dirty", Meaning = "脏的", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'dɜ:(r)ti/" },
        new Vocab { Word = "house", Meaning = "房屋；房子；住宅", Book = "六年级上册", Unit = "第一单元", Phonetic = "/haʊs/" },
        new Vocab { Word = "clock", Meaning = "钟表", Book = "六年级上册", Unit = "第一单元", Phonetic = "/klɒk/, /klɑ:k/" },
        new Vocab { Word = "table", Meaning = "桌子", Book = "六年级上册", Unit = "第一单元", Phonetic = "/teɪbl/" },
        new Vocab { Word = "lunch", Meaning = "午餐；午饭", Book = "六年级上册", Unit = "第一单元", Phonetic = "/lʌntʃ/" },
        new Vocab { Word = "put", Meaning = "放；安置；放置", Book = "六年级上册", Unit = "第一单元", Phonetic = "/pʊt/" },
        new Vocab { Word = "breakfast", Meaning = "早餐；早饭", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'brekfəst/" },
        new Vocab { Word = "dinner", Meaning = "正餐、晚餐", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'dɪnə(r)/" },
        new Vocab { Word = "me", Meaning = "我（的宾格）", Book = "六年级上册", Unit = "第一单元", Phonetic = "/em 'i:/" },
        new Vocab { Word = "them", Meaning = "他（她、它）们", Book = "六年级上册", Unit = "第一单元", Phonetic = "/ðem;ðəm/" },
        new Vocab { Word = "him", Meaning = "（用作宾语或表语）他", Book = "六年级上册", Unit = "第一单元", Phonetic = "/hɪm/" },
        new Vocab { Word = "half", Meaning = "一半；半数", Book = "六年级上册", Unit = "第一单元", Phonetic = "/hɑ:f/, /hæf/" },
        new Vocab { Word = "Mr.", Meaning = "先生", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'mɪstə(r)/" },
        new Vocab { Word = "Mrs.", Meaning = "太太；夫人", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'mɪsɪz/" },
        new Vocab { Word = "clean", Meaning = "干净", Book = "六年级上册", Unit = "第一单元", Phonetic = "/'klin/" },

        // 六年级上册 第二单元 （已修正）
        new Vocab { Word = "umbrella", Meaning = "伞；雨伞", Book = "六年级上册", Unit = "第二单元", Phonetic = "/ʌm'brelə/" },
        new Vocab { Word = "class", Meaning = "班；班级", Book = "六年级上册", Unit = "第二单元", Phonetic = "/klɑ:s/, /klæs/" },
        new Vocab { Word = "always", Meaning = "总是；永远；一直", Book = "六年级上册", Unit = "第二单元", Phonetic = "/'ɔ:lweɪz/" },
        new Vocab { Word = "ill", Meaning = "有病；不舒服", Book = "六年级上册", Unit = "第二单元", Phonetic = "/ɪl/" },
        new Vocab { Word = "driver", Meaning = "司机", Book = "六年级上册", Unit = "第二单元", Phonetic = "/'draɪvə(r)/" },
        new Vocab { Word = "lesson", Meaning = "课", Book = "六年级上册", Unit = "第二单元", Phonetic = "/'lesn/" },
        new Vocab { Word = "word", Meaning = "单词；字；话语", Book = "六年级上册", Unit = "第二单元", Phonetic = "/wɜ:(r)d/" },
        new Vocab { Word = "its", Meaning = "它的", Book = "六年级上册", Unit = "第二单元", Phonetic = "/ɪts/" },
        new Vocab { Word = "well", Meaning = "健康；身体好", Book = "六年级上册", Unit = "第二单元", Phonetic = "/wel/" },
        new Vocab { Word = "Ms.", Meaning = "（用于女子的姓氏或者姓名前，不指明婚否）女士", Book = "六年级上册", Unit = "第二单元", Phonetic = "/mɪz/" },
        new Vocab { Word = "sometimes", Meaning = "有时、间或", Book = "六年级上册", Unit = "第二单元", Phonetic = "/'sʌmtaɪmz/" },

        // 六年级上册 第三单元 （已修正）
        new Vocab { Word = "ear", Meaning = "耳朵", Book = "六年级上册", Unit = "第三单元", Phonetic = "/ɪə/, /ɪr/" },
        new Vocab { Word = "eye", Meaning = "眼睛", Book = "六年级上册", Unit = "第三单元", Phonetic = "/aɪ/" },
        new Vocab { Word = "mouth", Meaning = "嘴", Book = "六年级上册", Unit = "第三单元", Phonetic = "/maʊθ/" },
        new Vocab { Word = "nose", Meaning = "鼻子", Book = "六年级上册", Unit = "第三单元", Phonetic = "/nəʊz/" },
        new Vocab { Word = "can", Meaning = "能，会（过去式could）", Book = "六年级上册", Unit = "第三单元", Phonetic = "/kæn; kən/" },
        new Vocab { Word = "autumn", Meaning = "秋天、秋季", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'ɔ:təm/" },
        new Vocab { Word = "spring", Meaning = "春天、春季", Book = "六年级上册", Unit = "第三单元", Phonetic = "/sprɪŋ/" },
        new Vocab { Word = "summer", Meaning = "夏天、夏季", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'sʌmə(r)/" },
        new Vocab { Word = "winter", Meaning = "冬天、冬季", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'wɪntə(r)/" },
        new Vocab { Word = "season", Meaning = "季节", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'si:zn/" },
        new Vocab { Word = "arm", Meaning = "胳膊", Book = "六年级上册", Unit = "第三单元", Phonetic = "/ɑ:(r)m/" },
        new Vocab { Word = "body", Meaning = "身体", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'bɒdi/, /'bɑ:di/" },
        new Vocab { Word = "head", Meaning = "头", Book = "六年级上册", Unit = "第三单元", Phonetic = "/hed/" },
        new Vocab { Word = "leg", Meaning = "腿", Book = "六年级上册", Unit = "第三单元", Phonetic = "/leg/" },
        new Vocab { Word = "why", Meaning = "为什么", Book = "六年级上册", Unit = "第三单元", Phonetic = "/waɪ/" },
        new Vocab { Word = "think", Meaning = "认为、以为、想、思考", Book = "六年级上册", Unit = "第三单元", Phonetic = "/θɪŋk/" },
        new Vocab { Word = "again", Meaning = "再、又", Book = "六年级上册", Unit = "第三单元", Phonetic = "/ə'gen/, /ə'geɪn/" },
        new Vocab { Word = "put on", Meaning = "穿上、带上", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'pʊtɒn/" },
        new Vocab { Word = "take off", Meaning = "脱下（衣服）；摘掉", Book = "六年级上册", Unit = "第三单元", Phonetic = "/'teɪkɒf/" },

        // 六年级上册 第四单元 （已修正）
        new Vocab { Word = "tomorrow", Meaning = "明天", Book = "六年级上册", Unit = "第四单元", Phonetic = "/tə'mɒrəʊ/, /tə'mɑ:rəʊ/" },
        new Vocab { Word = "bring", Meaning = "带、带来（过去式bought）", Book = "六年级上册", Unit = "第四单元", Phonetic = "/brɪŋ/" },
        new Vocab { Word = "open", Meaning = "打开", Book = "六年级上册", Unit = "第四单元", Phonetic = "/'əʊpən/" },
        new Vocab { Word = "then", Meaning = "然后、接着", Book = "六年级上册", Unit = "第四单元", Phonetic = "/ðen/" },
        new Vocab { Word = "little", Meaning = "幼小的", Book = "六年级上册", Unit = "第四单元", Phonetic = "/'lɪtl/" },
        new Vocab { Word = "song", Meaning = "歌曲", Book = "六年级上册", Unit = "第四单元", Phonetic = "/sɒŋ/, /sɔ:ŋ/" },
        new Vocab { Word = "holiday", Meaning = "假日；节日", Book = "六年级上册", Unit = "第四单元", Phonetic = "/'hɒlədeɪ/, /'hɑ:lədeɪ/" },
        new Vocab { Word = "give", Meaning = "给、给予", Book = "六年级上册", Unit = "第四单元", Phonetic = "/gɪv/" },
        new Vocab { Word = "put up", Meaning = "装饰、张贴", Book = "六年级上册", Unit = "第四单元", Phonetic = "" },
   
        // 六年级下册 第一单元
        new Vocab { Word = "or", Meaning = "或者", Book = "六年级下册", Unit = "第一单元", Phonetic = "/ɔ:(r)/" },
        new Vocab { Word = "hand", Meaning = "手", Book = "六年级下册", Unit = "第一单元", Phonetic = "/hænd/" },
        new Vocab { Word = "wear", Meaning = "戴", Book = "六年级下册", Unit = "第一单元", Phonetic = "/weə/, /wer/" },
        new Vocab { Word = "basketball", Meaning = "篮球", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'bɑ:skɪtbɔ:l/, /'bæskɪbɔ:l/" },
        new Vocab { Word = "game", Meaning = "游戏", Book = "六年级下册", Unit = "第一单元", Phonetic = "/geɪm/" },
        new Vocab { Word = "policeman", Meaning = "警察", Book = "六年级下册", Unit = "第一单元", Phonetic = "/pə'li:smən/" },
        new Vocab { Word = "try", Meaning = "试；尝试", Book = "六年级下册", Unit = "第一单元", Phonetic = "/traɪ/" },
        new Vocab { Word = "ask", Meaning = "问", Book = "六年级下册", Unit = "第一单元", Phonetic = "/ɑ:sk/, /æsk/" },
        new Vocab { Word = "answer", Meaning = "问答", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'ɑ:nsə/, /'ænsər/" },
        new Vocab { Word = "football", Meaning = "足球", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'fʊtbɔ:l/" },
        new Vocab { Word = "sport", Meaning = "体育运动", Book = "六年级下册", Unit = "第一单元", Phonetic = "/spɔ:(r)t/" },
        new Vocab { Word = "difficult", Meaning = "困难", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'dɪfɪkəlt/" },
        new Vocab { Word = "easy", Meaning = "容易的", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'i:zi/" },
        new Vocab { Word = "heavy", Meaning = "重的", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'hevi/" },
        new Vocab { Word = "any", Meaning = "任何的；任一的", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'eni/" },
        new Vocab { Word = "some", Meaning = "adj.一些；某些pron.有些；有的", Book = "六年级下册", Unit = "第一单元", Phonetic = "/sʌm/" },
        new Vocab { Word = "very", Meaning = "adv.很；非常", Book = "六年级下册", Unit = "第一单元", Phonetic = "/'veri/" },

        // 六年级下册 第二单元
        new Vocab { Word = "bad", Meaning = "邪恶的；坏的", Book = "六年级下册", Unit = "第二单元", Phonetic = "/bæd/" },
        new Vocab { Word = "often", Meaning = "时常；常常", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'ɒfn/, /'ɔ:fn/" },
        new Vocab { Word = "before", Meaning = "在……之前", Book = "六年级下册", Unit = "第二单元", Phonetic = "/bɪ'fɔ:(r)/" },
        new Vocab { Word = "exercise", Meaning = "活动；运动", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'eksəsaɪz/" },
        new Vocab { Word = "strong", Meaning = "强壮的", Book = "六年级下册", Unit = "第二单元", Phonetic = "/strɒŋ/, /strɔ:ŋ/" },
        new Vocab { Word = "after", Meaning = "在（时间）后", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'ɑ:ftə(r)/, /'æftə(r)/" },
        new Vocab { Word = "minute", Meaning = "分钟；一会儿", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'mɪnɪt/" },
        new Vocab { Word = "healthy", Meaning = "健康的", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'helθi/" },
        new Vocab { Word = "next", Meaning = "下一个的；紧接着的；接下来的", Book = "六年级下册", Unit = "第二单元", Phonetic = "/nekst/" },
        new Vocab { Word = "high", Meaning = "高的", Book = "六年级下册", Unit = "第二单元", Phonetic = "/haɪ/" },
        new Vocab { Word = "hour", Meaning = "n.小时", Book = "六年级下册", Unit = "第二单元", Phonetic = "/'aʊə(r)/" },

        // 六年级下册 第三单元
        new Vocab { Word = "lake", Meaning = "湖；湖泊", Book = "六年级下册", Unit = "第三单元", Phonetic = "/leɪk/" },
        new Vocab { Word = "swim", Meaning = "游泳", Book = "六年级下册", Unit = "第三单元", Phonetic = "/swɪm/" },
        new Vocab { Word = "clever", Meaning = "聪明的；聪颖的", Book = "六年级下册", Unit = "第三单元", Phonetic = "/'klevə(r)/" },
        new Vocab { Word = "fan", Meaning = "风扇", Book = "六年级下册", Unit = "第三单元", Phonetic = "/fæn/" },
        new Vocab { Word = "angry", Meaning = "生气的", Book = "六年级下册", Unit = "第三单元", Phonetic = "/'æŋgri/" },
        new Vocab { Word = "ship", Meaning = "（大）船", Book = "六年级下册", Unit = "第三单元", Phonetic = "/ʃɪp/" },
        new Vocab { Word = "close", Meaning = "关；关闭", Book = "六年级下册", Unit = "第三单元", Phonetic = "/kləʊs/" },
        new Vocab { Word = "visit", Meaning = "拜访", Book = "六年级下册", Unit = "第三单元", Phonetic = "/'vɪzɪt/" },

        // 六年级下册 第四单元
        new Vocab { Word = "cake", Meaning = "蛋糕", Book = "六年级下册", Unit = "第四单元", Phonetic = "/keɪk/" },
        new Vocab { Word = "party", Meaning = "聚会；派对", Book = "六年级下册", Unit = "第四单元", Phonetic = "/'pɑ:(r)ti/" },
        new Vocab { Word = "late", Meaning = "晚；迟", Book = "六年级下册", Unit = "第四单元", Phonetic = "/leɪt/" },
        new Vocab { Word = "find", Meaning = "找到", Book = "六年级下册", Unit = "第四单元", Phonetic = "/faɪnd/" },
        new Vocab { Word = "get", Meaning = "到达", Book = "六年级下册", Unit = "第四单元", Phonetic = "/get/" },
        new Vocab { Word = "all", Meaning = "全；完全", Book = "六年级下册", Unit = "第四单元", Phonetic = "/ɔ:l/" },
        new Vocab { Word = "early", Meaning = "早到的", Book = "六年级下册", Unit = "第四单元", Phonetic = "/'ɜ:(r)li/" },
        new Vocab { Word = "hear", Meaning = "听见", Book = "六年级下册", Unit = "第四单元", Phonetic = "/hɪə/, /hɪr/" },
        new Vocab { Word = "every", Meaning = "每一个，每个", Book = "六年级下册", Unit = "第四单元", Phonetic = "/'evri/" },
        new Vocab { Word = "begin", Meaning = "开始", Book = "六年级下册", Unit = "第四单元", Phonetic = "/bɪ'gɪn/" },
        new Vocab { Word = "tell", Meaning = "告诉", Book = "六年级下册", Unit = "第四单元", Phonetic = "/tel/" },
        new Vocab { Word = "good-bye", Meaning = "再见", Book = "六年级下册", Unit = "第四单元", Phonetic = "" },
    };

    // 扩充词汇包：挑战模式每10个正常词混入1个扩充词
    public static readonly List<Vocab> ExtraVocabs = new()
    {
        //1. 动物与昆虫扩展
        new Vocab { Word = "Hippo", Meaning = "河马", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈhɪp.əʊ/" },
        new Vocab { Word = "Gorilla", Meaning = "大猩猩", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ɡəˈrɪl.ə/" },
        new Vocab { Word = "Crocodile", Meaning = "鳄鱼", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈkrɒk.ə.daɪl/" },
        new Vocab { Word = "Eagle", Meaning = "老鹰", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈiː.ɡl/" },
        new Vocab { Word = "Owl", Meaning = "猫头鹰", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/aʊl/" },
        new Vocab { Word = "Peacock", Meaning = "孔雀", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈpiː.kɒk/" },
        new Vocab { Word = "Swan", Meaning = "天鹅", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/swɒn/" },
        new Vocab { Word = "Penguin", Meaning = "企鹅", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈpeŋ.ɡwɪn/" },
        new Vocab { Word = "Seal", Meaning = "海豹", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/siːl/" },
        new Vocab { Word = "Octopus", Meaning = "章鱼", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈɒk.tə.pəs/" },
        new Vocab { Word = "Jellyfish", Meaning = "水母", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈdʒel.i.fɪʃ/" },
        new Vocab { Word = "Butterfly", Meaning = "蝴蝶", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈbʌt.ə.flaɪ/" },
        new Vocab { Word = "Dragonfly", Meaning = "蜻蜓", Book = "扩充词汇包", Unit = "动物扩展", Phonetic = "/ˈdræɡ.ən.flaɪ/" },

        //2. 日常物品与地点
        new Vocab { Word = "Apartment", Meaning = "公寓", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/əˈpɑːt.mənt/" },
        new Vocab { Word = "Elevator", Meaning = "电梯", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/ˈel.ɪ.veɪ.tər/" },
        new Vocab { Word = "Fountain", Meaning = "喷泉", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/ˈfaʊn.tən/" },
        new Vocab { Word = "Garden", Meaning = "花园", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/ˈɡɑː.dn/" },
        new Vocab { Word = "Bakery", Meaning = "面包店", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/ˈbeɪ.kər.i/" },
        new Vocab { Word = "Supermarket", Meaning = "超市", Book = "扩充词汇包", Unit = "生活场所", Phonetic = "/ˈsuː.pəˌmɑː.kɪt/" },
        new Vocab { Word = "Backpack", Meaning = "背包", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/ˈbæk.pæk/" },
        new Vocab { Word = "Key", Meaning = "钥匙", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/kiː/" },
        new Vocab { Word = "Mirror", Meaning = "镜子", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/ˈmɪr.ər/" },
        new Vocab { Word = "Blanket", Meaning = "毯子", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/ˈblæŋ.kɪt/" },
        new Vocab { Word = "Bottle", Meaning = "瓶子", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/ˈbɒt.l/" },
        new Vocab { Word = "Brush", Meaning = "刷子", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/brʌʃ/" },
        new Vocab { Word = "Comb", Meaning = "梳子", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/kəʊm/" },
        new Vocab { Word = "Soap", Meaning = "肥皂", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/səʊp/" },
        new Vocab { Word = "Towel", Meaning = "毛巾", Book = "扩充词汇包", Unit = "生活物品", Phonetic = "/ˈtaʊ.əl/" },

        //3. 食物拓展
        new Vocab { Word = "Dessert", Meaning = "甜点", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/dɪˈzɜːt/" },
        new Vocab { Word = "Yogurt", Meaning = "酸奶", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈjɒɡ.ət/" },
        new Vocab { Word = "Salad", Meaning = "沙拉", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈsæl.əd/" },
        new Vocab { Word = "Pancake", Meaning = "薄煎饼", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈpæn.keɪk/" },
        new Vocab { Word = "Cookie", Meaning = "小甜饼", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈkʊk.i/" },
        new Vocab { Word = "Chocolate", Meaning = "巧克力", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈtʃɒk.lət/" },
        new Vocab { Word = "Juice", Meaning = "果汁", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/dʒuːs/" },
        new Vocab { Word = "Popcorn", Meaning = "爆米花", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈpɒp.kɔːn/" },
        new Vocab { Word = "Cucumber", Meaning = "黄瓜", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈkjuː.kʌm.bər/" },
        new Vocab { Word = "Carrot", Meaning = "胡萝卜", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈkær.ət/" },
        new Vocab { Word = "Onion", Meaning = "洋葱", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈʌn.jən/" },
        new Vocab { Word = "Pizza", Meaning = "披萨", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈpiːt.sə/" },
        new Vocab { Word = "Hamburger", Meaning = "汉堡包", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈhæm.bɜː.ɡər/" },
        new Vocab { Word = "Sandwich", Meaning = "三明治", Book = "扩充词汇包", Unit = "食物拓展", Phonetic = "/ˈsæn.wɪtʃ/" },

        //4. 动词与动作
        new Vocab { Word = "Whisper", Meaning = "耳语，小声说", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/ˈwɪs.pər/" },
        new Vocab { Word = "Shout", Meaning = "喊叫", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/ʃaʊt/" },
        new Vocab { Word = "Giggle", Meaning = "咯咯笑", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/ˈɡɪɡ.l/" },
        new Vocab { Word = "Crawl", Meaning = "爬行", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/krɔːl/" },
        new Vocab { Word = "Hop", Meaning = "单脚跳", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/hɒp/" },
        new Vocab { Word = "Skip", Meaning = "蹦跳，跳绳", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/skɪp/" },
        new Vocab { Word = "Carry", Meaning = "搬运，携带", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/ˈkær.i/" },
        new Vocab { Word = "Push", Meaning = "推", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/pʊʃ/" },
        new Vocab { Word = "Pull", Meaning = "拉", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/pʊl/" },
        new Vocab { Word = "Throw", Meaning = "扔", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/θrəʊ/" },
        new Vocab { Word = "Catch", Meaning = "接住", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/kætʃ/" },
        new Vocab { Word = "Climb", Meaning = "爬", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/klaɪm/" },
        new Vocab { Word = "Pick up", Meaning = "捡起", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/pɪkʌp/" },
        new Vocab { Word = "Wave", Meaning = "挥手", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/weɪv/" },
        new Vocab { Word = "Build", Meaning = "建造", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/bɪld/" },
        new Vocab { Word = "Fix", Meaning = "修理", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/fɪks/" },
        new Vocab { Word = "Pour", Meaning = "倒", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/pɔːr/" },
        new Vocab { Word = "Stir", Meaning = "搅拌", Book = "扩充词汇包", Unit = "动词动作", Phonetic = "/stɜːr/" },

        //5.形容词
        new Vocab { Word = "Proud", Meaning = "自豪的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/praʊd/" },
        new Vocab { Word = "Excited", Meaning = "兴奋的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/ɪkˈsaɪ.tɪd/" },
        new Vocab { Word = "Scared", Meaning = "害怕的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/skeəd/" },
        new Vocab { Word = "Brave", Meaning = "勇敢的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/breɪv/" },
        new Vocab { Word = "Kind", Meaning = "友善的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/kaɪnd/" },
        new Vocab { Word = "Polite", Meaning = "有礼貌的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/pəˈlaɪt/" },
        new Vocab { Word = "Rude", Meaning = "粗鲁的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/ruːd/" },
        new Vocab { Word = "Messy", Meaning = "凌乱的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/ˈmes.i/" },
        new Vocab { Word = "Neat", Meaning = "整洁的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/niːt/" },
        new Vocab { Word = "Soft", Meaning = "柔软的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/sɒft/" },
        new Vocab { Word = "Hard", Meaning = "坚硬的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/hɑːd/" },
        new Vocab { Word = "Smooth", Meaning = "光滑的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/smuːð/" },
        new Vocab { Word = "Rough", Meaning = "粗糙的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/rʌf/" },
        new Vocab { Word = "Wet", Meaning = "湿的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/wet/" },
        new Vocab { Word = "Dry", Meaning = "干的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/draɪ/" },
        new Vocab { Word = "Noisy", Meaning = "吵闹的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/ˈnɔɪ.zi/" },
        new Vocab { Word = "Quiet", Meaning = "安静的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/ˈkwaɪ.ət/" },
        new Vocab { Word = "Loud", Meaning = "大声的", Book = "扩充词汇包", Unit = "形容词", Phonetic = "/laʊd/" },

        //6. 自然与世界
        new Vocab { Word = "Sky", Meaning = "天空", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/skaɪ/" },
        new Vocab { Word = "Cloud", Meaning = "云", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/klaʊd/" },
        new Vocab { Word = "Star", Meaning = "星星", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/stɑːr/" },
        new Vocab { Word = "Ground", Meaning = "地面", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/ɡraʊnd/" },
        new Vocab { Word = "Hill", Meaning = "小山", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/hɪl/" },
        new Vocab { Word = "Path", Meaning = "小路", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/pɑːθ/" },
        new Vocab { Word = "Field", Meaning = "田野", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/fiːld/" },
        new Vocab { Word = "Plant", Meaning = "植物", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/plɑːnt/" },
        new Vocab { Word = "Grass", Meaning = "草", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/ɡrɑːs/" },
        new Vocab { Word = "Leaf", Meaning = "叶子 (复数：Leaves)", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/liːf/" },
        new Vocab { Word = "Rock", Meaning = "岩石", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/rɒk/" },
        new Vocab { Word = "Shell", Meaning = "贝壳", Book = "扩充词汇包", Unit = "自然与世界", Phonetic = "/ʃel/" },

        //7. 人物与职业
        new Vocab { Word = "Pilot", Meaning = "飞行员", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈpaɪ.lət/" },
        new Vocab { Word = "Astronaut", Meaning = "宇航员", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈæs.trə.nɔːt/" },
        new Vocab { Word = "Artist", Meaning = "艺术家", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈɑː.tɪst/" },
        new Vocab { Word = "Singer", Meaning = "歌手", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈsɪŋ.ər/" },
        new Vocab { Word = "Dancer", Meaning = "舞蹈家", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈdɑːn.sər/" },
        new Vocab { Word = "Postman", Meaning = "邮递员", Book = "扩充词汇包", Unit = "人物与职业", Phonetic = "/ˈpəʊst.mən/" },

        //8. 时间与星期
        new Vocab { Word = "Today", Meaning = "今天", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/təˈdeɪ/" },
        new Vocab { Word = "Yesterday", Meaning = "昨天", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˈjes.tə.deɪ/" },
        new Vocab { Word = "Tomorrow", Meaning = "明天", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/təˈmɒr.əʊ/" },
        new Vocab { Word = "Weekend", Meaning = "周末", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˌwiːkˈend/" },
        new Vocab { Word = "Morning", Meaning = "早晨", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˈmɔː.nɪŋ/" },
        new Vocab { Word = "Evening", Meaning = "晚上", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˈiːv.nɪŋ/" },
        new Vocab { Word = "Night", Meaning = "夜晚", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/naɪt/" },
        new Vocab { Word = "Minute", Meaning = "分钟", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˈmɪn.ɪt/" },
        new Vocab { Word = "Hour", Meaning = "小时", Book = "扩充词汇包", Unit = "时间与星期", Phonetic = "/ˈaʊər/" },

        //9. 身体与健康
        new Vocab { Word = "Knee", Meaning = "膝盖", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/niː/" },
        new Vocab { Word = "Elbow", Meaning = "手肘", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/ˈel.bəʊ/" },
        new Vocab { Word = "Shoulder", Meaning = "肩膀", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/ˈʃəʊl.dər/" },
        new Vocab { Word = "Toe", Meaning = "脚趾", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/təʊ/" },
        new Vocab { Word = "Finger", Meaning = "手指", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/ˈfɪŋ.ɡər/" },
        new Vocab { Word = "Tooth", Meaning = "牙齿", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/tuːθ/" },
        new Vocab { Word = "Headache", Meaning = "头痛", Book = "扩充词汇包", Unit = "身体与健康", Phonetic = "/ˈhed.eɪk/" },
    };
}

